name: Update roadmap.sh badge with timestamp

on:
  push:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write  # Grants write permissions for pushing changes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update URL in README.md
        run: |
          TIMESTAMP=$(node -p "Date.now()")
          BASE_URL="https://roadmap.sh/card/tall/6722b75631d65c235dc18635?variant=dark"
          NEW_URL="${BASE_URL}$timestamp=${TIMESTAMP}"
          sed -i "s|${BASE_URL}.*|${UPDATED_URL}|" README.md
          
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update roadmap.sh badge with new timestamp"
          git push
